name: biocad_bcr_pipeline_environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - biopython
  - mafft
  - iqtree
  - mrbayes
  - igblast
  - blast
  - toytree
  - toyplot
  - matplotlib
  - seaborn
  - macse